### ISSUE TITLE
Does this mean it’s revoked it says signed on website…

### ISSUE THREAD

**Issue by GreatNateDev** [DebianArch64/Scarlet#22]
![IMG_2534](https://github.com/DebianArch64/Scarlet/assets/99703235/a7725c25-4a3c-45bf-a94d-5b0ef7e11af6)

**Comment by GreatNateDev** [comment]
And yes I clicked trust in settings
![IMG_2535](https://github.com/DebianArch64/Scarlet/assets/99703235/4d4b757a-c99a-410f-84a8-35bf12ab28e8)

**Comment by DebianArch64** [comment]
This isn't a revoke

**Comment by GreatNateDev** [comment]
How do I unblacklist my device or is that not possible

**Comment by DebianArch64** [comment]
> How do I unblacklist my device or is that not possible

It's possible - since the device is the one doing it to itself it's as simple as removing the file on the device that lists out what certificates are blacklisted. If you have an MDC device you can do this with the 'Whitelist' or 'Blacklist' app (you'll need some way to sideload those apps though). If you have a jailbreak you can remove the file with Filza.

A reset also wipes out the file, but doesn't stop it from happening again. 

At the end best option is just to move away from 'Direct Install' and onto getting your own certificate and using that with Scarlet - you can also wait until Scarlet Direct is signed with a different certificate

**Comment by GreatNateDev** [comment]
Dang ok

**Comment by GreatNateDev** [comment]
Sideloadly it is :)

**Comment by GreatNateDev** [comment]
[Link](https://c187.pcloud.com/dHZRPAuMlZhKhDiiZZZ4NGIo7Z2ZZOAzZkZUPdCVZz8R8ftws1KJNtrUu7bGJ7y9x1mIy/Blacklist_1.0.ipa) for people that have the same problem that's the ipa file use sideloadly or cydia impactor to sideload this and then use it and scarlet should be fixed!

**Comment by GreatNateDev** [comment]
Turns out my version is not supported hanging on by when scarlet is not blacklisted and by my pc lol but pure kfd blacklist app might work just having problems with that too
