### ISSUE TITLE
This app cannot be installed because its integrity could not be verified.

### ISSUE THREAD

**Issue by lts20050703** [DebianArch64/Scarlet#3]
Sorry if this is in the wrong place, I do not have a twitter account and do not know where to submit this issue

I'm using direct version btw

![image](https://user-images.githubusercontent.com/87189679/210614293-2761caf8-86ac-4f10-99e1-d24e7b299e91.jpeg)
![image](https://user-images.githubusercontent.com/87189679/210614310-a95b4b0c-9eed-4036-a0c5-197266f9e3f3.jpeg)

**Comment by DebianArch64** [comment]
> Sorry if this is in the wrong place, I do not have a twitter account and do not know where to submit this issue
> 
> I'm using direct version btw
> 
> ![image](https://user-images.githubusercontent.com/87189679/210614293-2761caf8-86ac-4f10-99e1-d24e7b299e91.jpeg) ![image](https://user-images.githubusercontent.com/87189679/210614310-a95b4b0c-9eed-4036-a0c5-197266f9e3f3.jpeg)

That message usually means a revocation has happened with the certificate the app is using. It's odd because one of my friends installed it three hours ago, but I guess apple could have revoked it minutes ago

You can contact me on Twitter with the mailbox icon on my profile - stuff like this I can't control which is why it's recommended to use the computer method
