### ISSUE TITLE
Install fails with message:

### ISSUE THREAD

**Issue by SkyKingPX** [DebianArch64/Scarlet#62]
App cannot be installed because its integrity could not be verified.

Every time I try to install Scarlet, this message comes up (I am trying for months now)

I am using an iPhone 11 and an iPad 9th Generation.

Am I doing something wrong?

**Comment by DebianArch64** [comment]
> App cannot be installed because its integrity could not be verified.
> 
> Every time I try to install Scarlet, this message comes up (I am trying for months now)
> 
> I am using an iPhone 11 and an iPad 9th Generation.
> 
> Am I doing something wrong?

Direct install is signed with enterprise certificates, they are available publicly and everyone uses them so they get revoked very often and are hard to replace because only major companies can get them if interviewing with apple

If you want something reliable don't use direct install, use a computer or buy a certificate with maplesign to import

https://docs.usescarlet.com/scarlet/certificates-developer-login
