### ISSUE TITLE
How can I make my own third party App Store?

### ISSUE THREAD

**Issue by Jamison-smith** [DebianArch64/Scarlet#63]
I would like to make my own third party App Store to do random stuff, how should I do it?

**Comment by DebianArch64** [comment]
> I would like to make my own third party App Store to do random stuff, how should I do it?

Pretty much you generate an install plist that says the location of the IPA, and you codesign the IPA with a certificate. You put the plist into the item-services url scheme (you can search this up, apple should have official guide since this is used officially to distribute apps to developers by companies)

If you plan on using enterprise certificates for it make sure to have your server randomize the bundleId so it has reduced chances of "internet connection" stuff apple has to detect if user will use app for bad purposes
